Landing header
d3rpp-dev/bse-205-elective-project pull request #11
Opened 2024-11-18 20:24 UTC by JSpring0303

2024-11-18 20:29 UTC, d3rpp commented on src/routes/(app)/app/account/create_key_dialog.svelte
> +>>>>>>> cd6736bb39d0423671ae1834afa4f5a47e45f3a7
My man this is what a merge conflict looks like

2024-11-18 20:32 UTC, d3rpp commented on src/routes/(landing)/+layout.svelte
> +<div class="bg-cover bg-center h-full" style="background-image: url('/src/lib/backgroundsAndAssets/landerDecoBackgroundV2.svg'), linear-gradient(to right, #000000 30%, #6CFF96 100%); background-posit
this won't work in a build, you'll need to add the asset to the `static` folder and reference it from there.

It works in dev, but not in a build

2024-11-18 20:32 UTC, d3rpp commented on src/routes/(landing)/+page.svelte
> +		style="font-family: futura, sans-serif; font-weight: 400; font-style: normal; font-size: 4.75rem; text-align: left; color: white; text-shadow: -4px 5px 7px rgba(0, 0, 0, 0.4);">
why we using inline styles?

2024-11-18 20:33 UTC, d3rpp requested changes
my man

2024-11-18 20:35 UTC, JSpring0303 commented on src/routes/(landing)/+layout.svelte
> +<div class="bg-cover bg-center h-full" style="background-image: url('/src/lib/backgroundsAndAssets/landerDecoBackgroundV2.svg'), linear-gradient(to right, #000000 30%, #6CFF96 100%); background-posit
The only problem is that it keeps going on about a vite allow list when i keep it in static

2024-11-18 20:36 UTC, JSpring0303 commented on src/routes/(landing)/+page.svelte
> +		style="font-family: futura, sans-serif; font-weight: 400; font-style: normal; font-size: 4.75rem; text-align: left; color: white; text-shadow: -4px 5px 7px rgba(0, 0, 0, 0.4);">
habit

2024-11-19 09:23 UTC, d3rpp approved these changes
LGTM :+1:

2024-11-19 09:24 UTC, merged